# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c098b561c977ef575a6c94f886e724fef8a185495215e2c200562b2a8cb3f8220c882d2e0d56d45d06bc1328f8e5eb0fc79a5ebdf94bdcd2cc0af5a8c125044c

test:
  secret_key_base: 98cd8c119caa7bd0e7889de5f2b04ebe112db0e8f03db51d158fc03d224596d35996504fd35c65051e1b9c72e877b6fa064456bcab80cf60a8b706ea2895fdab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
